#! /usr/local/bin/python

import sys

def share(url):
    with open("db", "a") as myfile:
	myfile.write(url + "\n")

""" Possibily unsafe, use with caution """
def parse_args():
    # test for valid length
    if len(sys.argv) != 2:
	sys.stderr.write("usage: share <url>")
	sys.exit()
    if sys.argv[1] == "clear":
	return 0
    else:
    	return 1

""" Read from db and create links """
def build_html():
    html =  """
		<html>
		    <title>Share - easily access articles you want to read 
				    from your tablet
		    </title>
		    <style type="text/css">
		    * {{
			font-size: 36pt;
		    }}
		    </style>
		    <body>
			{0}
		    </body>
		</html>
	    """
    with open("db") as db:
	for url in db:
	    ahref = "<a href={0}>{0}</a>".format(url)
	    html = html.format(ahref + "<br><br>{0}")
	    html = html.replace("{", "{{", 1).replace("}", "}}", 1)
    html = html.format("")
    return html


def write_html(html):
    with open("index.html", "w") as myfile:
    	myfile.write(html)

def clear_db():
    with open("db", "w") as myfile:
    	myfile.write("")

def main():
    if parse_args() == 0:
    	clear_db()
    else:
	share(sys.argv[1])
	html = build_html()
	write_html(html)

if __name__ == "__main__":
    main()
